name: fyp
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter_email_sender: ^5.0.2
  authentication_repository:
    path: packages/authentication_repository
  bloc: ^8.0.2
  equatable: ^2.0.3
  flow_builder: ^0.0.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  font_awesome_flutter: ^9.1.0
  form_inputs:
    path: packages/form_inputs
  formz: ^0.4.0
  google_fonts: ^2.1.0
  meta: ^1.3.0
  very_good_analysis: ^2.4.0
  fluttertoast: ^8.0.9
  image_cropper: ^1.0.2
  image_picker: ^0.8.5
  image_crop: ^0.4.0
  shared_preferences: 2.0.11
  auto_size_text: 3.0.0
  built_collection: 5.1.1
  built_value: 8.1.3
  cached_network_image: 3.1.0+1
  cloud_firestore: ^4.1.0
  file_picker: 4.5.1
  intl: 0.17.0
  json_path: 0.2.1
  firebase_storage: ^11.0.6
  page_transition: 2.0.4
  google_sign_in: 5.2.1
  json_serializable: 6.1.3
  cool_dropdown: ^1.4.2
  mime_type: 1.0.0
  rxdart: 0.26.0
  firebase_core: ^2.3.0
  custom_radio_grouped_button: ^2.1.2+2
  sign_in_with_apple:
    git:
      url: https://github.com/asmengistu/dart_packages
      ref: ab18d53a80e0a4bb90f1ad84f37f1b408930f28d
      path: packages/sign_in_with_apple/sign_in_with_apple/
  smooth_page_indicator: 1.0.0+2
  timeago: 3.1.0
  url_launcher: 6.0.15
  flutter_google_places: ^0.3.0
  flutter_spinkit: ^5.1.0
  fancy_drawer: ^2.0.0
  scan: ^1.6.0
  bloc_test: ^9.1.0
  syncfusion_flutter_datepicker: ^20.3.56
  day_night_time_picker: ^1.1.3
  simple_gradient_text: ^1.2.4
  firebase_database: ^10.0.6
  simple_animations: ^5.0.0+2
dev_dependencies:
  bloc_test: ^9.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/

dependency_overrides:
  bloc: ^8.0.2
  bloc_test: ^9.0.2
  flutter_bloc: ^8.0.1